core/urls.py
from django.urls import path, include
from core.views import about_us, add_to_wishlist, base, callback, cart_view, add_to_cart, ajax_add_review, category_list_view, category_product_list_view, checkout, contact, customer_dashboard, delete_item_from_cart, filter_product, footer, index, make_address_default, order_detail, order_payment, payment_completed_view, payment_failed_view, privacy_policy, product_detail_view, product_list_view, remove_from_wishlist, tag_list, search_view, update_cart, wishlist_view

app_name = 'core'

urlpatterns = [
    #Homepage
    path('', index, name='index'),
    path('products/', product_list_view, name='product_list'),
    path('product/<pid>/', product_detail_view, name='product_detail'),
    
    #Category
    path('category/', category_list_view, name='category_list'),
    path('category/<cid>/', category_product_list_view, name='category_product_list'),
    
    #Tags
    path('products/tag/<slug:tag_slug>/', tag_list, name="tags"),

    #Add Review
    path("ajax-add-review/<int:pid>", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),

    # Add to cart url
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    # Cart page url
    path("cart/", cart_view, name="cart"),

    # Delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update cart
    path("update-cart/", update_cart, name="update-cart"),

    # # checkout URL
    # path("checkout/", checkout_view, name="checkout"),

    # # checkout URL
    # path("checkout/<oid>", checkout, name="checkout"),

    # checkout URL
    path("checkout/", checkout, name="checkout"),

    # path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),

    

    # Dashboard URL
    path("dashboard/", customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    # Making addresses default
    path("make-default-address/", make_address_default, name="make-default-address"),

    #PayPal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

    # # Payment Successfull
    # path("payment-completed/", payment_completed_view, name="payment-completed"),

    # Payment Successfull
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/<oid>/", payment_failed_view, name="payment-failed"),

    path("contact/", contact, name="contact"),

    path("payment/", order_payment, name="payment"),
    path("razorpay/callback/", callback, name="callback"),

    #wishlist
    path('wishlist/', wishlist_view, name="wishlist"),

    #ading to wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    #Removing from wishlist
    path("remove-from-wishlist/", remove_from_wishlist, name="remove-wishlist"),

    path("filter-products/", filter_product, name="filter-product"),

    path("footer/", footer),
    path('privacy-policy', privacy_policy, name="privacy-policy"),
    path('about-us', about_us, name="about-us"),
    path('base', base),

]   

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file")
]

if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sign-out/', views.logout_view, name='sign-out'),
    path('change-password/', views.change_password, name='change-password'),

    path("profile/update/", views.profile_update, name="profile-update"),

    
]

core/forms.py
from dataclasses import fields
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Write your review here...'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from collections import defaultdict
import dis
from email import message
import json
import re
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.db.models import Count, Avg, Min, Max
from core.models import Coupon,Product,Category,Vendor,CartOrder, CartOrderItems,ProductImages,ProductReview,Wishlist,Address
from taggit.models import Tag
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
import razorpay
import calendar
from django.db.models.functions import ExtractMonth

from userauths.models import ContactUs, Profile
from django.core import serializers

from django.contrib.contenttypes.models import ContentType

# Create your views here.

def index(request):
    # product = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status="published", featured=True)
    categories = Category.objects.all()

    for product in products:
        product_review_stats = ProductReview.objects.filter(product=product).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        product.avg_rating = product_review_stats['avg_rating'] or 0
        product.review_count = product_review_stats['review_count'] or 0

    context = {
        "products":products,
        "categories":categories
    }
    return render(request, 'core/index.html', context)

def category_list_view(request):
    categories = Category.objects.all()

    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)

def product_list_view(request):
    products = Product.objects.filter(product_status="published")

    for product in products:
        product_review_stats = ProductReview.objects.filter(product=product).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        product.avg_rating = product_review_stats['avg_rating'] or 0
        product.review_count = product_review_stats['review_count'] or 0

    context = {
        "products":products
    }
    return render(request, 'core/shop.html', context)

def category_product_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status="published", category=category)
    
    # Retrieve the content type of the product model
    product_content_type = ContentType.objects.get_for_model(Product)

    # Fetch the tags associated with the filtered products and annotate the product count
    tags = (
        Tag.objects.filter(taggit_taggeditem_items__content_type=product_content_type, taggit_taggeditem_items__object_id__in=products)
                .annotate(product_count=Count('taggit_taggeditem_items__object_id', distinct=True))
                .order_by('name')
    )

    min_max_price = products.aggregate(Min("price"), Max("price"))

    for product in products:
        product_review_stats = ProductReview.objects.filter(product=product).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        product.avg_rating = product_review_stats['avg_rating'] or 0
        product.review_count = product_review_stats['review_count'] or 0

    context = {
        "products":products,
        "categories":category,
        "tags":tags,
        "min_max_price":min_max_price,
    }
    return render(request, 'core/category-product-list.html', context)

def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    # product = get_object_or_404(Product, pid=pid)
    # category = Category.objects.get(cid=cid)

    related_products = Product.objects.filter(category=product.category).exclude(pid=pid)
    for p in related_products:
        product_review_stats = ProductReview.objects.filter(product=p).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        p.avg_rating = product_review_stats['avg_rating'] or 0
        p.review_count = product_review_stats['review_count'] or 0

    categories = Category.objects.all()

    p_images = product.p_images.all()

    # Getting all reviews related to a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    
    # Getting average review
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    # Product Review form
    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False
    
    product_review_stats = ProductReview.objects.filter(product=product).aggregate(
        avg_rating=Avg('rating'),
        review_count=Count('id')
    )

    product.avg_rating = product_review_stats['avg_rating'] or 0
    product.review_count = product_review_stats['review_count'] or 0

    context = {
        "product":product,
        "p_images":p_images,
        "related_products":related_products,
        "reviews":reviews,
        "average_rating":average_rating,
        "review_form":review_form,
        "make_review":make_review,
        "categories":categories,
    }
    return render(request, 'core/product-detail.html', context)

def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")


    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    
    # Extract unique categories for the matched products
    # Calculate product count for each category
    categories = defaultdict(int)
    for product in products:
        categories[product.category] += 1

    # Convert the defaultdict to a list of tuples
    categories = list(categories.items())

    min_max_price = products.aggregate(Min("price"), Max("price"))

    for product in products:
        product_review_stats = ProductReview.objects.filter(product=product).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        product.avg_rating = product_review_stats['avg_rating'] or 0
        product.review_count = product_review_stats['review_count'] or 0

    context = {
        "products":products,
        "tags":tag,
        "categories":categories,
        "min_max_price":min_max_price,
    }

    return render(request, "core/tag.html", context)

def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        'user':user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
            'bool': True,
            'context': context,
            'average_reviews': average_reviews,
        }

    )

def search_view(request):
    query=request.GET.get('q')

    # products=Product.objects.filter(product_status="published", title__icontains=query, description__icontains=query).order_by("-date")
    
    # Filter the products based on our query
    products = Product.objects.filter(
        product_status="published",
        title__icontains=query,
        description__icontains=query
    ).order_by("-date")

    # Extract unique categories for the matched products
    # Calculate product count for each category
    categories = defaultdict(int)
    for product in products:
        categories[product.category] += 1

    # Convert the defaultdict to a list of tuples
    categories = list(categories.items())

    

    

    # Retrieve the content type of the product model
    product_content_type = ContentType.objects.get_for_model(Product)

    # Fetch the tags associated with the filtered products and annotate the product count
    tags = (
        Tag.objects.filter(taggit_taggeditem_items__content_type=product_content_type, taggit_taggeditem_items__object_id__in=products)
                .annotate(product_count=Count('taggit_taggeditem_items__object_id', distinct=True))
                .order_by('name')
    )

    min_max_price = products.aggregate(Min("price"), Max("price"))

    for product in products:
        product_review_stats = ProductReview.objects.filter(product=product).aggregate(
            avg_rating=Avg('rating'),
            review_count=Count('id')
        )
        product.avg_rating = product_review_stats['avg_rating'] or 0
        product.review_count = product_review_stats['review_count'] or 0


    context = {
        'products':products,
        'query':query,
        'categories':categories,
        'tags':tags,
        "min_max_price": min_max_price,
    }

    return render(request, "core/search.html", context)

def add_to_cart(request):
    cart_product = {}

    pid=request.GET['pid']
    price=float(Product.objects.get(pid=pid).price)
    image=str(Product.objects.get(pid=pid).image.url)

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],

templates/core/cart.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
<title>Your Cart</title>
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/cart.css' %}">
{% endblock css %}

{% block main %}

  <main id="cart-list">
    <div class="heading-banner-container">
      <div class="heading-banner">
      <div class="heading-banner-content">
        <span class="heading">Your Cart</span>
        <p>There are <span id="paraspan">{{ totalcartitems }}</span> product{{ totalcartitems | pluralize:"s"}} in your cart!</p>
      </div>
      </div>
    </div>

    <section class="cart">
    {% if  cart_data.items %}
      <div class="cart-products-heading">
        <span id="product-name-heading">Product</span>
        <span id="product-price-heading">Price</span>
        <span id="product-quantity-heading">Quantity</span>
        <span id="product-subtotal-heading">Subtotal</span>
        {% comment %} <span id="product-refresh-heading">Refresh</span> {% endcomment %}
        <span id="product-remove-heading">Remove</span>
      </div>
      {% endif %}

      {% for product_id, item in cart_data.items%}
      <div class="cart-products" data-product="{{ product_id }}">
        
        <div class="product">
          <img src="{{ item.image }}" alt="product" height="70" />
          <a href="{% url 'core:product_detail' item.pid %}" class="product-name">{{ item.title }}</a>
        </div>
        
        <span class="product-price">Rs. {{ item.price | floatformat:2}}</span>
        <div class="product-quantity">
          <input type="text" value="{{ item.qty }}" readonly class="qty product-qty-{{ product_id }}"/>
          <div class="arrows-container">
            <i class="fa-solid fa-chevron-up arrow up"></i>
            <i class="fa-solid fa-chevron-down arrow down"></i>
          </div>
        </div>
        <span class="product-subtotal">Rs. {% widthratio item.price 1 item.qty %} </span>
        {% comment %} <button class=" update-product" data-product="{{ product_id }}">
          <i class="fa-solid fa-arrows-rotate"></i>
        </button> {% endcomment %}
        <button class="delete-product" data-product="{{ product_id }}">
          {% comment %} <i class="fa-solid fa-xmark"></i> {% endcomment %}
          <i class="fa-solid fa-trash-can"></i>
        </button>
      </div> 
      {% empty %}
      <div class="empty">
      <span>Nothing in cart!</span>
      <button onclick="window.location.href = '{% url 'core:product_list' %}'">Shop Now</button>
      </div>
      {% endfor %}


      {% if  cart_data.items %}
      {% comment %} <div id="cart-operations">
        <div id="coupon-container">
          <input type="text" placeholder="Coupon Code" />
          <button>Apply Coupon</button>
        </div> 
        <button id="empty-cart">Empty Cart</button>
      </div> {% endcomment %}

      <div id="cart-totals-container">
        <h2>Cart totals</h2>
        <div id="cart-totals">
          <span id="subtotal">Subtotal</span>
          <span id="subtotal-value">Rs. {{ cart_total_amount | floatformat:2 }}</span>
          <span id="shipping">Shipping</span>
          <div id="shipping-values">
            <span>Free Shipping</span>
            {% comment %} <span>Shipping to <span id="address">CA</span>.</span> {% endcomment %}
            <span id="change-address"><a href="{% url 'core:dashboard' %}">Change address <i class="fa-solid fa-truck"></i></a></span>
          </div>
          <span id="total">Total</span>
          <span id="total-value">Rs. {{ cart_total_amount | floatformat:2 }}</span>
        </div>

        {% if totalcartitems %}
        <div id="proceed-checkout">
          <button id="proceed-checkout-btn" onclick="window.location.href = '{% url 'core:checkout' %}'">Proceed to checkout</button>
        </div>
        {% endif %}
        
      </div>
      {% endif %}
    </section>
    </main>

{% endblock main %}

templates/core/checkout.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
<title>Checkout</title>
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/checkout.css' %}">
{% endblock css %}

{% block main %}

<div class="heading-banner-container">
    <div class="heading-banner">
        <div class="heading-banner-content">
            <span class="heading">Checkout</span>
            <p>There are <span id="paraspan">{{ totalcartitems }}</span> product{{ totalcartitems | pluralize:"s"}} in
                your cart!</p>
        </div>
    </div>
</div>

<section class="checkout-container">
    <form id="customer-details-checkout" method="POST">
        <h2>Billing Details</h2>
        {% csrf_token %}
        <input type="text" name="full_name" placeholder="Full Name *" required
            value="{{request.user.username | title}}" maxlength="100">
        <input type="tel" name="phone" placeholder="Phone *" required value="{{active_address.mobile}}" min="60000000000" max="9999999999" minlength="10", maxlength="10">
        <input type="email" name="email" placeholder="Email address *" required maxlength="100">

        <input type="text" name="address" placeholder="Address *" required value="{{active_address.address}}" maxlength="100">
        <input type="text" name="city" placeholder="City / Town *" required maxlength="100">
        {% comment %} <input type="text" name="address2" placeholder="Address line 2"> {% endcomment %}
        <input list="state" name="state" placeholder="State *" required maxlength="100">
        <datalist id="state" name="state" required>
            <option value="select state"></option>
            <option value="s1"></option>
            <option value="s2"></option>
            <option value="s3"></option>
        </datalist>

        <input list="country" name="country" placeholder="Country *" required maxlength="100">
        <datalist id="country" required>
            <option value="select country"></option>
            <option value="c1"></option>
            <option value="c2"></option>
            <option value="c3"></option>
        </datalist>



        <input type="number" name="pincode" placeholder="Postcode / ZIP *" required min="111111" max="999999">
        <input type="hidden" name="customer-details-checkout">

    </form>

    <aside class="order">
        <div id="order-heading">
            <h2>Your Order</h2>
            <span>Subtotal - <span>Rs. {{order.price | floatformat:2}}</span></span>
        </div>

        {% for o in order_items %}
        <div class="cart-products">
            <div class="product-img">
                <img src="{{o.image }}" alt="product" height="70">
            </div>
            <a class="product-name" href="{% url 'core:product_detail' o.pid %}">{{ o.item }}</a>
            <span class="product-price">Rs. {{ o.price }}</span>
            <div class="product-quantity">
                <i class="fa-solid fa-xmark"></i><span> {{ o.qty }}</span>
            </div>
            <span class="product-subtotal">Rs. {{ o.total }}</span>
        </div>
        {% endfor %}


    </aside>

    <div>
        <div id="cart-operations">
            <div id="coupon-container">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" name="code" placeholder="Enter Coupon Code..." maxlength="50" />
                    <button type="submit" name="apply-coupon">Apply Coupon</button>
                </form>
            </div>

        </div>

        <div class="place-back">
            {% comment %} <button id="place-order">Place an Order </button> {% endcomment %}
            {% comment %} {{paypal_payment_button.render}} {% endcomment %}
            {% comment %} <div id="paypal-button-container"></div> {% endcomment %}
            <button id="rzp-button1" type="submit" form="customer-details-checkout">Pay with Razorpay</button>
            <button id="back" onclick="window.location.href = `{% url 'core:cart' %}`">Go back to cart </button>
        </div>

    </div>

    <div id="cart-totals-container">
        <h2>Order Summary</h2>
        <div id="cart-totals">
          <span id="subtotal">Subtotal</span>
          <span id="subtotal-value">Rs. {{order.price | floatformat:2}}</span>
          <span id="shipping">Shipping</span>
          <div id="shipping-values">
            <span>Free Shipping</span>
            {% comment %} <span>Shipping to <span id="address">CA</span>.</span> {% endcomment %}
            <span id="change-address"><a href="{% url 'core:dashboard' %}">Change address <i class="fa-solid fa-truck"></i></a></span>
          </div>
          <span id="discount">Discount</span>
          <span id="discount-value">Rs. {{order.saved | floatformat:2}}</span>
          <span id="total">Total</span>
          <span id="total-value">Rs. {{order.total | floatformat:2}}</span>
        </div>
</section>

{% endblock %}

templates/core/index.html
{% extends '../base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/index.css' %}">
{% endblock css %}

{% block main %}

<section id="section1">
    <div id="section1-left">
        <ul id="category" type="none">
            <h1>Category</h1>

            {% for c in categories %}
            <li>
                <a href="{% url 'core:category_product_list' c.cid %}">
                    <img src="{{c.image.url}}" />
                    <span>{{c.title}}</span>
                </a>
                <div class="category-circle">{{c.category.count}}</div>
            </li>

            {% endfor %}
        </ul>
    </div>
    <div id="section1-right">
        <div class="slider">
            <div class="slider-content active"
                style="background-image: url({% static 'assets/imgs/banner-10-min.png' %})">
                <div class="slider-banner-content">
                    <span class="slider-title">Stay home and get your daily needs from our shop</span>

                    <p>Start Your Daily Shopping with <span id="paraspan">GroceryDash</span></p>
                    <button onclick="window.location.href = '{% url 'core:product_list' %}'">Shop Now</button>
                </div>
                <img src="{% static 'assets/imgs/banner-9-min.png' %}" alt="delivery-boy">
            </div>

            <div class="slider-content" style="background-image: url({% static 'assets/imgs/img2.png' %})">
                <div class="slider-banner-content">
                    <span class="slider-title">Stay home and get your daily needs from our shop</span>

                    <p>Start Your Daily Shopping with <span id="paraspan">GroceryDash</span></p>

                    <button onclick="window.location.href = '{% url 'core:product_list' %}'">Shop Now</button>

                </div>
            </div>
            <!-- Add more slider-content divs for additional slides -->
            <div class="slider-nav">
                <div class="slider-circle active"></div>
                <div class="slider-circle"></div>
                <!-- Add more slider-circle divs for additional slides -->
            </div>
        </div>

        <span id="popular-products-heading">Popular Products</span>

        <div id="popular-products">

            {% for p in products %}
            <div class="products products-wrap" data-index="{{ p.id }}">
                <div class="product-img">
                    <a href="{% url 'core:product_detail' p.pid %}"><img src="{{ p.image.url }}" alt="product" height="200" /></a>
                    {% comment %} <img src="" alt="" class="hover-img" /> {% endcomment %}
                </div>
                <div class="product-content">
                    <p class="category-name">{{ p.category }}</p>
                    <a href="{% url 'core:product_detail' p.pid %}" class="product-title">{{ p.title }}</a>
                    <div class="rating">
                        <i class="fa-regular fa-star"></i>
                        <i class="fa-regular fa-star"></i>
                        <i class="fa-regular fa-star"></i>
                        <i class="fa-regular fa-star"></i>
                        <i class="fa-regular fa-star"></i>
                        <span class="rating-value">&nbsp;{{p.avg_rating | floatformat:1}} &nbsp;({{p.review_count | floatformat:0}})</span>
                    </div>
                    
                    {% if p.tags.all %}
                    <p class="tag-name">Tags:
                        <span>
                            {% for tag in p.tags.all %}
                            <a href="{% url 'core:tags' tag.slug%}" class="tag">#{{tag}}{% if not forloop.last %}, {% endif %}</a>
                            {% endfor %}
                        </span>
                    </p>
                    {% else %}
                    <p></p>
                    {% endif%}

                    <div class="price-cart">
                        <h3>Rs. <span class="price-{{p.id}}">{{p.price}}</span></h3>
                        {% if p.price < p.old_price %}<h4 class="old-price">Rs. {{p.old_price}}</h4>{% endif %}
                            <input type="hidden" id="quantity" class="quantity-{{ p.id }}" value="1">
                            <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                            <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                            <input type="hidden" class="product-id-{{ p.id }}" value="{{ p.id }}">
                            <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
                    </div>
                    <div class="buttons">
                        <button id="add-to-cart-btn" class="add-to-cart-btn" data-index="{{ p.id }}">Add to cart
                            &nbsp;<i class="fa-solid fa-cart-shopping"></i></button>
                        <button id="add-to-wishlist-btn" class="add-to-wishlist-btn"
                            data-product-item="{{ p.id }}"><span></span> <i class="fa-regular fa-heart"></i></button>

                    </div>

                </div>
                {% if p.price < p.old_price %} 
                <div class="discount"><span>-{{ p.get_percentage|floatformat:0 }}%</div>
                {% endif %}
        </div>
        {% endfor %}

    </div>

    </div>
    </div>
</section>

<script>
        document.addEventListener("DOMContentLoaded", () => {
            let slides = document.querySelectorAll(".slider-content");
            let circles = document.querySelectorAll(".slider-circle");
            let currentSlide = 0;

            // Set the first circle as active initially
            circles[currentSlide].classList.add("active");

            const slideInterval = setInterval(nextSlide, 5000); // Change slide every 3 seconds

            function nextSlide() {
                goToSlide((currentSlide + 1) % slides.length);
            }

            function goToSlide(n) {
                slides[currentSlide].classList.remove("active");
                circles[currentSlide].classList.remove("active");
                currentSlide = n;
                slides[currentSlide].classList.add("active");
                circles[currentSlide].classList.add("active");
            }

            // Add click event listeners to circles
            circles.forEach((circle, index) => {
                circle.addEventListener("click", () => {
                    goToSlide(index);
                    clearInterval(slideInterval); // Stop the automatic sliding
                });
            });


            var ratingElements = document.querySelectorAll(".rating");
            ratingElements.forEach((ratingElement) => {
                var ratingValue = parseFloat(ratingElement.querySelector(".rating-value").innerText);
                var truncValue = Math.trunc(ratingValue);
                var stars = ratingElement.querySelectorAll("i");

                for (let i = 0; i < truncValue; i++) {
                    stars[i].classList.remove("fa-regular");
                    stars[i].classList.add("fa-solid");
                }

                if (ratingValue !== truncValue) {
                    stars[truncValue].classList.remove("fa-regular");
                    stars[truncValue].classList.add("fa-solid");
                    stars[truncValue].classList.remove("fa-star");
                    stars[truncValue].classList.add("fa-star-half-stroke");
                }

            });
        });

    </script>

{% endblock main %}